spring.application.name=spring_boot_demo
#server.port = 8082spring.servlet.multipart.enabled=true
 
spring.datasource.url=jdbc:postgresql://localhost:5433/spring_boot_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

 




spring.servlet.multipart.max-file-size=300MB
spring.servlet.multipart.max-request-size=300MB
spring.servlet.multipart.file-size-threshold=1KB


